---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.23.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600-charts
        namespace: flux-system
  values:
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: ${SVC_PIHOLE_IP}
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: ${SVC_PIHOLE_IP}
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    persistentVolumeClaim:
      enabled: true
    adminPassword: ${SECRET_PIHOLE_ADMIN_PASSWORD}
    extraEnvVars:
      RATE_LIMIT: "0/0"
  valuesFrom:
    - kind: Secret
      name: pihole-secrets
