---
- name: media
  hosts: media
  become: true
  roles:
    - role: docker-htpc

- name: wireguard
  hosts: wireguard
  become: true
  roles:
    - role: docker-wireguard

- name: ddclient
  hosts: ddclient
  become: true
  roles:
    - role: ddclient
