---
- name: common
  hosts: threekings
  become: true
  roles:
    - common

- name: resolvconf
  hosts: threekings
  roles:
    - resolvconf

- name: ddclient
  hosts: ddclient.threekings.ccag119.info
  roles:
    - ddclient

- name: telegraf
  hosts: threekings
  become: true
  roles:
    - telegraf

- name: media
  hosts: media.threekings.ccag119.info
  roles:
    - role: docker-htpc
      vars:
        include_plex: true

- name: wireguard
  hosts: wireguard.threekings.ccag119.info
  roles:
    - docker-wireguard

- name: prometheus node exporter
  hosts: threekings
  become: true
  roles:
    - cloudalchemy.node_exporter

- name: Grafana + Prometheus
  hosts: monitoring.threekings.ccag119.info
  become: true
  roles:
    - docker-grafana-prometheus
