---
- name: common
  hosts: threekings
  become: true
  roles:
    - common

- name: resolvconf
  hosts: threekings
  roles:
    - resolvconf

- name: ddclient
  hosts: ddclient
  roles:
    - ddclient

- name: telegraf
  hosts: threekings
  become: true
  roles:
    - telegraf

- name: media
  hosts: media
  become: true
  roles:
    - role: docker-htpc

- name: wireguard
  hosts: wireguard
  roles:
    - docker-wireguard

- name: prometheus node exporter
  hosts: threekings
  become: true
  roles:
    - cloudalchemy.node_exporter

- name: Grafana + Prometheus
  hosts: monitoring
  become: true
  roles:
    - docker-grafana-prometheus
