---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ng
spec:
  interval: 8h
  timeout: 15m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: paperless-ng
