---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pihole-pv
  namespace: default
spec:
  storageClassName: pihole
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: /Volume 1/k3s/pihole
  mountOptions:
    - nfsvers=4.1
    - hard
