---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pihole-pv
  namespace: default
spec:
  storageClassName: pihole
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: /Volume 1/k3s/pihole
  resources:
    requests:
      storage: 500Mi
