- name: Install ddclient
  apt:
    name: ddclient
    state: present

- name: Copy ddclient.conf
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    owner: root
    group: root
  become: true
  notify: restart ddclient
