apiVersion: v1
data:
    OPENAI_API_KEY: ENC[AES256_GCM,data:3cKb+Sc2NCRYjVmJ7M+r9JsO+SLAbjC9Gb+ghuOOyO7cArULsxETJ7cYmt6h6XFwm8lbudqwI4v9uLDiVZ6upkdWlhp/AVz1bKBGH7u5Y017fACgtV6QW4D8bin3d8QBGT/GMRh4tiHyE/dO2XKSApNi5Tp5Ivwfp1nEo/I73LMOzezhv7Hjym5TB7MzNw1phGeXSoHyKAZDNgEMLRlOvd7zo/I=,iv:DJ+SP6Gr30Ci+smeDIM585zvRfrEaAo5ro6cd+kQd0w=,tag:lLXFVKTbQVgLOScuQ6D93g==,type:str]
kind: Secret
metadata:
    name: email-organizer
    namespace: email-organizer
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T15:58:31Z"
    mac: ENC[AES256_GCM,data:qMSO4Y+msqBBLFOaufyXdut8nNGtsbsoHQ0KNm2ruNMG5qTpWWMP8yomPct2PyuKepnOZJ/0B2J4603N4VgVf4zVk8J5SpjN1r4stClvNWd1UkS8wWH6+MlFvUtMptH8vKydTOff9OpjCFqnSgg36LrX/T6woSJQEoyG3uoIc+0=,iv:yr8QP9hqTtHy5yyGbmQ1RCCm4Gj/pSh8vjQM9Bqaf4c=,tag:Rf6aSXkQZHTYsIhye2ezgw==,type:str]
    pgp:
        - created_at: "2026-07-02T15:58:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ//fFsvVvADil81tYTohHufimyJXwEu3+47X9rSQ5jnqERl
            8fwnBAr8wab00kpVgcTOOHLSyR0CRUpypIDAcdtHie7FxFtvMeQs8oaT09AnoEBc
            iuBNNf19/RSgFyj6nenz0cW3zknww5Lbepqrm7dKviERrww4p+XDb6UIVdM+9mYX
            GJta/hikpEVFnd9rNmJrUlgUbYxjKX8IxtIxHFntGQN5iuXz2ULzVRAgZdc6S1HF
            ClI4xgI8x04gW9XPJ86y8dgoVHDPwvyDHHhAs5pa85juZPD13jVvkKhvIAlHaerc
            RBv2fKRwxySbpd/a2mVw1+76Z7/UtnVIAPqWW5hxeuSuL93rogsiBT1p3s1Oyehw
            e+ffTrE4kCF9qkB3OuRwJ7QaMZwivMjeYtdUjw+Tj2IM5xSAKzkpb+AngnxkIPE0
            Y5VblGY0hVjep+jvkFkTci6F+bjdFI1HCNyby1/RPPC4qvkxzs9CYNsic2aOeaXd
            KMiUwCJO4VWUZlRWZ+qzzg5URjEQsA4LjQi3Nwj+ck2a0RtP/p9aXVuviMlDqv7s
            ovvjXNiSPXal0iLxZr2hd5/QWALSUM/oq0+TFxke75tO6c44Fcx9WOI64DDShtG2
            nu4Z8tmILMQtWaigu3qLmP+Gdki43lNpmgOXkTB6X2R19f1SHB4YTuT+Ek6EiaDU
            aAEJAhCVXR99GnIl/ZVbnRwMaDupwkJhcww0BzBxHveyPkGEaCKwSlA5Vh+oxXFp
            tWQ17OlCZperFDe4/jn4WaQ7q6LwzrugFqlvcW5dpd/8gcW9Np4+rK8Xt+T5M8QK
            2nAWFn6mrStA
            =qJUY
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    version: 3.13.2
