apiVersion: v1
kind: Secret
metadata:
    name: email-organizer
    namespace: email-organizer
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:c5zAva1Y+cmcyrcVEe3M1LNAOVYSbBtSLQIoqzpGAocfHoRR4Ux1j6IsTP/Yck+no/5pZW2wD1/EEFpBgJb90eam4IZCz0VvjbkHQPai3B5EwhYkadSH/KhmepYouXFPzZUsAk/1wS4OwJ9M+yrAMOxVrPnDwU+/zazEl0LSeb/xYSBlUp2VgI36hfO+gFdnnZfuoDgIz0SdVG2IxhBACYT/mrs=,iv:gmhDu19lXpV+ICi8wS3qSHe2NHoblcGIbCePy7xBuf0=,tag:LBOhqjBOMdj0swl0V6SODg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T16:11:24Z"
    mac: ENC[AES256_GCM,data:tvE1S0DQf+XDq53VZn5BrM3q4sugUcwD27ebZ4vBkYS7F60zLjz5Mztgc8CYap44VaMF8kGaedIFh4X2olsj8wcn5Xb8qAgCfnFXl7PgKDYXv6hD5tCi+hDkjzioMjdCXxtrPPqLRTNTV/poEn+FDJTKtFsr2n6tE03iVLMp9Bw=,iv:mcfw751mKoYbSSLctQYDy9Bl3a8SZRGZeYgQvW/rrsE=,tag:kBP9kg+nPsBwaFoh7fGTMg==,type:str]
    pgp:
        - created_at: "2026-07-02T16:11:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJARAAnLwcWz5Opewr+Ev/XOXMQTz0HhGkypjEvruO77A51ke3
            17euIKHDtu3pABd968leRy4xQDqIzZ+H3DzxlLDvZ0/zoS+1j8RmksSggxJ2yz+J
            k5sorWgr7vXw027vk/J0twmSs4Lfszwt3kCEXFPhMuel4lbhOQQvy4R0E/NdgdLX
            dlf9dAJBFBFlFc/Um1TvrqANCbzdCL8oRaggNX92WcGJuEr6bpL1HB5QohGEycss
            H5g0njREBSxXUQpUvFqgBZANkYKzD6g8U9ezgEaoNt3+puAgkWcaxe/Zq0LZr5Ph
            5TmNcsZyX4ytFWljnSnhki8SS2w2TzYOmVJ0k4e8faxOhcTfVxervB5ApnjxvSEe
            9eI/uk3uzUzL03Gr+8dDYdrIYauln4uNRdtaKZ3qaGmmQREJlEERbL+dbjRcpyIO
            hOp5kbPUpsV2gBU3wVhNpvw6LFaXK025hF3jOAEEtLEs7B+INH8x4K54CL3QYMvy
            /Z/HgTu4xgNYihws8XuYdt6nvr5zYiOxB4e4VlKECopbx8ufK0FBysK+V4Xdbpbq
            HnQfv1JsJjPTnd5tgCN4tEHiGmFfMbR3ZQk40mKG5awpCh2CMddcTws5ZoA79Vv1
            2hry0Z8POP8sXeMNqXRIAIf8CaRiFxiPG0YShVSFIgSr9SGrzShspj+WHhLwvgbU
            aAEJAhC/ubC7mitmiQC/R2ykIjclnMGE/gFSxY/dLmkfSzxUtCA57IqJiTYR+NO5
            9pbpbH8eHVhVIdAvhX1s/WXlpaCuNzT7gieCAJ+QBHX0TOW2VSBUyiYvI6pTevvc
            LzlvF0I+HSEq
            =NYPK
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    version: 3.13.2
