apiVersion: v1
kind: Secret
metadata:
    name: camping-bot-secrets
    namespace: camping-bot
type: Opaque
stringData:
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:ZuIIS6lUaSvfhAnyn0ceV60JyWX/Y0/LuPtZni064hD/9Q==,iv:29X/1Q8WyUChuLwHRxrcQVCwaUgVoPdQOrQ5sgTosOs=,tag:incgdccIt93h5pCgJLrFyg==,type:str]
    TWILIO_AUTH_TOKEN: ENC[AES256_GCM,data:Dr7QJ0DW6SFiVAug6bnViKGPtQWUkO21e+iBzaROKso=,iv:Gnzq3maJGj1CFIdzx1YUfWKqhhY3gv7dWYKXDE8Muug=,tag:1JeGMMxRr86ZQfNGJF1j9w==,type:str]
    TWILIO_FROM_NUMBER: ENC[AES256_GCM,data:9hCT2rr0yfvq7lKC,iv:hBm6wZwb/beQalFBkye4ld59KRXhTXmZfaplMpidk/k=,tag:cGPf3UD8rLwLyeUBZO/Wcw==,type:str]
    TWILIO_TO_NUMBER: ENC[AES256_GCM,data:eWb2xcBcNtfLRh8z,iv:w1T1isL24h2VEWvAk+VwPaALxybaE4XUtFLMdtZJVEI=,tag:5Cc31emSvXqyhBkVx/MZJw==,type:str]
    RECGOV_USERNAME: ENC[AES256_GCM,data:uFwRcpBrRZuwDul4+yc9gZGOcg==,iv:lKRmBTo7O3TvU/j/XCpsyHemj+dQj42W84EY08BMaYM=,tag:Pl2VtmV88/cmkePtMWu33g==,type:str]
    RECGOV_PASSWORD: ENC[AES256_GCM,data:oO3Jqvpo8CORQv3SX1hk,iv:MuhUNP9Ll1rFcyeZtZTbWRmf0hPR8FlGtUMEaQtrj2I=,tag:5kp/eKUgpN5FEMF73+Nkjg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T01:24:43Z"
    mac: ENC[AES256_GCM,data:HyPToT6ka8JUt2LbbXN9pEFaxJG/D9rZHCCXAl6ifPbvLioZO6GEVYnE9tunzmWmebPaBmdiiDQ/bq3MUUBuJgP0LKEYT4rJHeyLYgdFBxc9Th2tI54TCA2IuqMxwcoPs60yFqrhz+fHRDyQhXmkinYf2klcq2GuhzmR/ZTg1Gc=,iv:FdE9dSP/wkODWG0K490naO9GGc27Dui7PYv2et3O1U8=,tag:rGNMJCpZ/PoNlYhtUhejuA==,type:str]
    pgp:
        - created_at: "2026-05-18T01:24:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ//V45MEuIM0MxqYP0jlDpYuWdNxQ4ruM8ueSHxVxkAdKbq
            CZG7/rbEnQ0AV11jWrxOU+GCO8Zb3Cwwve0QviJ8190RqMyOG1G2KWfTux9dv10m
            fehWEzMUS4lWfJP9lqEuUyNP99O90cx7MvRaHwGa9eZrRzczeql6IbdQTwJXitOD
            Cz/1u8efCcdRLcWczyIwBQY6Spsu61i9zfWVJeWeoNdT+IEn7UZ6cblmFKsae9PP
            KPDlBusOrsY1HDHeOHU0uOPy813yvSJcv7A/SbjOnZ651cqknGthXBEoCZmJIk3K
            CDQLeAqFz+XaTFX8Nh/7P/G/gi4F6evtxzmw2AYDR6hqY2BSj9SFMYdTZqA6lTlv
            KJAaicFrQzhqZ/IhMsRkgCPqV3jrWRu4F7a4/qGL02NkdfUhlyDOAI21O886vc56
            jvDmKkEUH6rMJ4pxbvKG7Ntd1QzNTLZiYjZp8JZx1bARYlUdW6iu3BkAv4/7Gsr0
            fNx/xHVqpBj5eWbxW1LTupgpIhkf+U8uGXHm5Wuuh7nzhULNYAEUYQt9itR9Dd1X
            CUgB59CCiLomNORicptvqz+uta7HrLk8YSi47eAeDNf5hZwcigiwDMk2l9Uql0oz
            hTqw43S5iFxSMckYcGX2YO2vkaP8FKCcCH5Kua4ae6sGm5Q1Ai9VCyT2WEyngGTU
            aAEJAhDnfCmxUbwQEfF8fq3etTBfESvznZrmMh4w3IncxC4LKJgk0y3VZFWr4Ywk
            9vNWAl7AdBohNyj1SWgITB5s19cZZFGviXpaFcFG+k880j3maxycr5toCAgd5Flk
            QUYGIuB+IXsd
            =EEGR
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    version: 3.13.0
