apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-pushover
    namespace: monitoring
type: Opaque
stringData:
    user_key: ENC[AES256_GCM,data:lp2/2LEzh2XOk1njVSErrOJMpq3URUqEB9Pt7A87,iv:GDYjlqk+r3LvybPC6Lf4urx4fv4kD6rStP8bgtTVMJg=,tag:NMmrZL9EIv2Q+FoeS1odwA==,type:str]
    token: ENC[AES256_GCM,data:oJr2EFcJbDxWx8r9WWsQOsf9BXJe1FZjzWs6wodd,iv:ByYpu19ZmRq8WizOdODSPzeuvPu+TZi7aSX1Kce5KJY=,tag:ARqYvmdFybxUfDLkjaH/dg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T02:03:45Z"
    mac: ENC[AES256_GCM,data:DchazyDPglV4sdgs6nCODhtmA+Yq7i26ijADNEr9vfrpBrVwFsJovZy3wUqJiBStBtPNo8P/C+AQ2a1gxCfl82Pwa8hsDDbDFhQaBsZh0MG9eafdRFd1QXxvuCZaSZuYu7rcesMPhVbdPM2P5yiNdpYFJl5oHlw6/X67sYthXHk=,iv:yRJ+EZiTnD0cOl5GPQuotXBf6iOjXG87ZDDoYc0/KCY=,tag:PsU8RQDu7IroZZx/4FXy4g==,type:str]
    pgp:
        - created_at: "2026-07-27T02:03:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ//TBRHK18k+XZ+h4y5qpwt/FzrkqfEeJGZHaP6GSiJ/hlI
            wH3qXOhOoTuu/BAoEXMQY3SrXe5ULK+khMzjCdApr2mwVwaxHELjvzjUsuBwCbj3
            ux9CYljTiGZb7gk7Ew56kT41a/Eq8tS4b3Dt/gegPGUTM83otod1phbJlYzxLKOk
            jqvkBI0B7FJU5UF3N4kvEYwowuoDI4HoYRdbwUrB9A3w6gHfxFm5WRKtW5ajZHVA
            zb6wbL6EBskGPPKRRZ0q8KaITzigMnOXKkzynbilFW23Eohl7MTNUsuIKusj9Nre
            bwBXb/p1DTySkNIsTdBwNzmY3B8InH7YWnpPxljcselfSlNMKroOzCHDQyk7PAvz
            p1+pg7gqL7uIJNyEk98k1L6h+rKCRk2GkU0oy4Mb7M6ywhCl2fAQ5aTuFWUiCbZi
            d6WxhGWqIz6+ZStKpXmex76qCPLMjKXuvf9hPlIhFMCbkPL3s9aLMelOluaRcEuP
            zDvLCxnkvpEzi/upetiSvt9cHnmC+0X1YHJD+wVDmLO8sI+fGhr/9nrz79Wu6DLY
            mhntMmyUciMZJi8jQo6MxJJA84Hk+kH3cy7GX5BnBCrjSe4Acl8dwREVjj4ed9gp
            4bm4dAhWkCAyUa7KExMBl5Q40Svw1Cq9zLtX9j4g7tbm/iiyXc/WlRZTYCn8SdLU
            aAEJAhAbki45JTpKUShGYmFBw0fB8oM+x6tEB9ULS2sCPnzM2hBcWq/QM++5PvOw
            5UixGuQYnfU3D/OijLuVMRvB7mwV1Bq+M/AnPGsoq4QffZdCBD/ynah3qAQQoZuN
            aFe5CwKLyzcB
            =yEnG
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    version: 3.13.2
