---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: 0.14.4
  values:
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          memory: 32Mi
    speaker:
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          memory: 64Mi
