---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: paperless-ng
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: postgresql
      version: 16.0.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: paperless-ng
