- stat:
    path: "{{ docker_htpc_home }}"
  register: _docker_htpc_home

- name: Create Docker container volumes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
  with_items:
    - path: "{{ docker_htpc_home }}"
    - path: "{{ docker_htpc_home }}/wireguard/config"
    - path: "{{ docker_htpc_home }}/deluge/config"
    - path: "{{ docker_htpc_home }}/jackett/config"
    - path: "{{ docker_htpc_home }}/sonarr/config"
    - path: "{{ docker_htpc_home }}/radarr/config"
    - path: "{{ docker_htpc_home }}/ombi/config"
    - path: "{{ docker_htpc_home }}/plex/config"
      create: include_plex
  when: item.create | default(True) | bool

- name: Copy Wireguard configurations
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.path }}"
    backup: true
  with_items:
    - src: mullvad_ca_all.conf
      path: "{{ docker_htpc_home }}/vpn/config/mullvad_ca_all.conf"
    - src: mullvad_ca.crt
      path: "{{ docker_htpc_home }}/vpn/config/mullvad_ca.crt"

- name: Copy Mullvad credentials
  template:
    src: mullvad_userpass.txt.j2
    dest: "{{ docker_htpc_home }}/vpn/config/mullvad_userpass.txt"
    backup: true

- name: Install kernel headers
  apt:
    name: linux-headers-{{ ansible_facts.ansible_kernel }}
    state: present

- name: Copy Deluge configurations
  template:
    src: deluge/config/core.conf.j2
    dest: "{{ docker_htpc_home }}/deluge/config/core.conf"
    backup: true

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_htpc_home }}/docker-compose.yml"
    backup: true
  register: _docker_htpc_docker_compose

- name: Start docker-compose
  docker_compose:
    project_src: "{{ docker_htpc_home }}"
    restarted: yes
  when: _docker_htpc_docker_compose.changed
