---
k3s_server_location: "/var/lib/rancher/k3s"
k3s_version: v1.32.12+k3s1
systemd_dir: "/etc/systemd/system"
token: token
cluster_init: false
k3s_server_endpoint: 192.168.4.65 # server-0 pinned IP; flips to kube-vip VIP after rollout
k3s_server_port: 6443
server_config_yaml: |
  disable:
    - servicelb
    - traefik
  tls-san:
    - "{{ kube_vip_address }}"

kube_vip_address: 192.168.4.5
kube_vip_interface: eth0
kube_vip_version: v1.2.1
