---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: paperless-ng
spec:
  interval: 8h
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 18.6.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: paperless-ng
