---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  namespace: default
  name: podinfo
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: 6.6.1
  values:
    service:
      annotations:
        metallb.universe.tf/address-pool: default
      type: LoadBalancer
