---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr@sha256:01a46a2865d9a6db5eb8ead04ec0dd33b8fbe233e8565ae70b50d4cc0af4cfb0
          env:
            - name: LOG_LEVEL
              value: info
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 8191
              name: http
          resources:
            requests:
              memory: 300Mi
              cpu: 50m
            limits:
              memory: 1Gi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: byparr
  namespace: media
spec:
  selector:
    app: byparr
  ports:
    - port: 8191
      targetPort: 8191
      name: http
