---
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install docker and docker-compose Python modules
  pip:
    name:
      - docker
      - docker-compose
    state: present
