- name: Configure apt repositories and packages
  ansible.builtin.include_tasks: apt.yml

- name: Configure network offload
  ansible.builtin.include_tasks: network.yml

- name: Configure storage content types
  ansible.builtin.include_tasks: storage.yml

- name: Configure IOMMU and vfio for PCI passthrough
  ansible.builtin.include_tasks: iommu.yml
