apiVersion: v1
data:
    SECRET_PIHOLE_ADMIN_PASSWORD: ENC[AES256_GCM,data:oDxUj51JkEmi07jeL/jDxINI+37xKztMbcI1iFNYTtY=,iv:efE/TwAmuD6xfN17v7DPfhOCINvARTmnYvATt/frqX4=,tag:CNNHh9lYlRSjmLBehxp3fg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-21T00:40:08Z"
    mac: ENC[AES256_GCM,data:yTp6E6zQxJJ3FE1nYK0ZXVOKUKSzJ9sLCm4xNA9CuGCJQvUiVF0Gwj5gAqB4fKxxBO9KKgutI+KDEphJ+OFXYA52tyrD3YF+PA+Fe/475HgxIOuxSyRG4mPO7jFlwmQ7n1dYuP/OcVn8Ex6aTLsUu5lte000e8nwGl88SGQ9l4k=,iv:9trxHPIGjnnP/z/0qXw5QE0H1lGJJBCj63aEIYci/ys=,tag:Z1cCM6MMK5sQfSrTgVuNkg==,type:str]
    pgp:
        - created_at: "2024-04-19T11:46:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJARAAlkhWOp1HBp4tyAphxFsfOHtTnAWSZnbpszZwlRt+6Kls
            pouU0KRxWZby/EisVXKnIEBwfzu01cRToaoFkouOOjhmGNg09xSjix9xPP+nA1yI
            Adq9Y6yFuZcdVyIUm+AIGJCmLJquGz0vlH+OsPRdprIj0exlMV4dJLp90QwvGSAn
            qUMlsPT0pc/MfKKP8st8AAaW0O9aon7QHCZ8/7v4maQzCyMZpGDhiD91hznT8HrW
            5s1ivNCu6nx6IuOh1w3Jizl4p2XmlHOkBdK7n/lkGe7IZQuwLtb+oB7NybKzJ3OZ
            2EBpvJmYhn/dFZJHmAjjKarZJVInvGNviZU0TKUP+LiSxpbjlH1tg8FfUY98/zE5
            upFkiGlEImYcxB5/CE2mhzx9qrzQIjCjou2j5jpjVnbqxeBmJO/jaYoi3eSlE7R3
            rAHyIzB5vQ642Kirv35a3ypZ2MOiV1RpqrkLDVRghmFQo3Jj4nSnMq/CWs317pKz
            6AWcA/UQyVZiOgBTRKvRJ2pcbWyPVsS8MmPyQI8FjT57uQj89TesuzdPI+S182vE
            tItdl8319exKJO6oNQqujTxkRLjGarORlm8IIxL/IBr/CHJUG8aDnf6VPj/DTnjy
            mD0GEAwh4NE/aGeXFBVokoRtzST3xWLoRNNbb2YK8o23v8TBMIsi3dk9nCO/8oLU
            aAEJAhCcZPcdKw32sjCJlTfzm9JrJRMXMpiUVS1acT4UGlqEBFOFdkOZKDPipTm9
            b9qsQwEFKOZdFc1oOJHIU623CmjEE4nFdIxi16TKj7Ebl8UiLDuquTe5ejo4seru
            SEmkR79TTAP6
            =Zoib
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
