---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-library
  namespace: media
spec:
  storageClassName: plex-library
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
